import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import axios from 'axios'

type article = {
  id: string,
  title: string,
  url: string,
  description?: string,
  reactionCount?: number,
  coverImage?: string,
  source: string
}

const Home: NextPage = () => {
  const [article, setArticle] = useState<article[]>()
  useEffect(() => {
    const fetchAPI = async () => {     
      const response = await axios.get(`http://localhost:8000/api/articles`)
      setArticle(response.data)
    }

    fetchAPI()
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div>
          {article?.map(item => {
            return (
              <div key={item.id}>
                <ul>
                  <li>
                    <img
                      src={item.coverImage || 'https://www.freeiconspng.com/uploads/no-image-icon-6.png'}
                      alt={item.title}
                    />
                  </li>
                  <li>
                    <h2>{item.title}</h2>
                  </li>
                  {item.description && (
                  <li>
                    <h4>{item.description}</h4>
                  </li>
                  )}
                  <li>
                    <h5>Reaction {item.reactionCount || 'unavailable'}</h5>
                  </li>
                  <li>
                    <span>
                      Source: {item.source}
                    </span>
                  </li> 
                </ul>
                <hr />
              </div>
            )
          })}
          
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home
